export const FETCH_GNOMES_REQUEST = 'FETCH_GNOMES_REQUEST'
export const FETCH_GNOMES_SUCCESS = 'FETCH_GNOMES_SUCCESS'
export const FETCH_GNOMES_FAILURE = 'FETCH_GNOMES_FAILURE'

export const SET_GNOME = 'SET_GNOME'
